services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${MBP_PG_USER}
      POSTGRES_DB: ${MBP_PG_NAME}
      POSTGRES_PASSWORD: ${MBP_PG_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      MBP_PG_NAME: ${MBP_PG_NAME}
      MBP_PG_USER: ${MBP_PG_USER}
      MBP_PG_PASSWORD: ${MBP_PG_PASSWORD}
      MBP_PG_PORT: ${MBP_PG_PORT:-5432}
      MBP_PG_HOST: ${MBP_PG_HOST_DOCKER:-db}
    depends_on:
      - db

volumes:
  db:
    driver: local
  pgadmin:
    driver: local